USE CRM
GO

/***** FUNCTION Auto_idNHANVIEN *****/
Select * From [dbo].[NHANVIEN]

CREATE FUNCTION Auto_idNHANVIEN()
RETURNS NVARCHAR(6)
AS
BEGIN
	DECLARE @ID VARCHAR(6),
			@ROLE VARCHAR(2)
	SET @ROLE = 'NV'
	IF (SELECT COUNT(NHANVIEN.id_NHANVIEN) FROM NHANVIEN) = 0
		SET @ID = '0'
	ELSE
		SELECT  @ID =  MAX(RIGHT(NHANVIEN.id_NHANVIEN, 4)) FROM NHANVIEN
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN @ROLE +'000' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9  THEN @ROLE +'00' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 99 THEN @ROLE + '0' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
		END
	RETURN @ID
END

Select dbo.Auto_idNHANVIEN();
--DROP FUNCTION Auto_idNHANVIEN;

/***** FUNCTION Auto_idKHACHHANG *****/
Select * From [dbo].[KHACHHANG]

CREATE FUNCTION Auto_idKHACHHANG()
RETURNS NVARCHAR(6)
AS
BEGIN
	DECLARE @ID VARCHAR(6),
			@ROLE VARCHAR(2)
	SET @ROLE = 'KH'
	IF (SELECT COUNT(KHACHHANG.id_KHACHHANG) FROM KHACHHANG) = 0
		SET @ID = '0'
	ELSE
		SELECT  @ID =  MAX(RIGHT(KHACHHANG.id_KHACHHANG, 4)) FROM KHACHHANG
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN @ROLE +'000' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9  THEN @ROLE +'00' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 99 THEN @ROLE + '0' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
		END
	RETURN @ID
END

Select dbo.Auto_idKHACHHANG();
--DROP FUNCTION Auto_idKHACHHANG;

/***** FUNCTION Auto_idKHUYENMAI *****/
Select * From [dbo].[KHUYENMAI]

ALTER FUNCTION Auto_idKHUYENMAI()
RETURNS NVARCHAR(6)
AS
BEGIN
	DECLARE @ID VARCHAR(6),
			@ROLE VARCHAR(2)
	SET @ROLE = 'KM'
	IF (SELECT COUNT(KHUYENMAI.id_KHUYENMAI) FROM KHUYENMAI) = 0
		SET @ID = '0'
	ELSE
		SELECT  @ID =  MAX(RIGHT(KHUYENMAI.id_KHUYENMAI, 4)) FROM KHUYENMAI
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN @ROLE +'000' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9  THEN @ROLE +'00' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 99 THEN @ROLE + '0' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
		END
	RETURN @ID
END

Select dbo.Auto_idKHUYENMAI();
--DROP FUNCTION Auto_idKHACHHANG;

